### PR TITLE
Diameter

### PR DESCRIPTION
**Pull request by rjm2718**
Couple of bugfixes here and new features for Grouped, Time, and Enumerated AVP types.

### CODE REVIEW

**Comment by tadamra** [comment]
@rjm2718 could you provide a test for the features you added. you can refer to the tests I provided. I you need any help, do not hesitate to write me.

**Comment by tadamra** [comment]
@rjm2718 I will wait few day for the unit tests for grouped and enumerated types. It is alright if you do not provide any, but it is better to add a test for each peace of code we add. If you do not get the chance to provide any in the next few days, then I will just take your changes.

**Comment by rjm2718** [comment]
@tadamra I just added a couple of more changes and additions, and now have unit tests that address the changes.  Let me know if you want me to change anything or add more tests.

**Comment by tadamra** [comment]
I pulled the changes and tested them locally. very well done 👍

**Pull request merged**
